/************************************************/
/*** Per concludere, provvediamo              ***/
/*** alle categorie del negozio,              ***/
/*** alle foto dei negozio,                   ***/
/*** all'indicazione dei comuni di consegna,  ***/
/*** ai social network dei negozi             ***/
/************************************************/

/*Insert 6: r_e_shops_e_categories */
insert into r_e_shops_e_categories(r_e_shops_e_categories_e_shops_id, r_e_shops_e_categories_e_categories_id, r_e_shops_e_categories_main_category, r_e_shops_e_categories_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_categories_id from e_categories where e_categories_code = 'RIST' and e_categories_visible = 1), 1, 1);
insert into r_e_shops_e_categories(r_e_shops_e_categories_e_shops_id, r_e_shops_e_categories_e_categories_id, r_e_shops_e_categories_main_category, r_e_shops_e_categories_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Er Vino de Pino' and e_shops_visible = 1), (select e_categories_id from e_categories where e_categories_code = 'AZVN' and e_categories_visible = 1), 1, 1);
insert into r_e_shops_e_categories(r_e_shops_e_categories_e_shops_id, r_e_shops_e_categories_e_categories_id, r_e_shops_e_categories_main_category, r_e_shops_e_categories_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Er Vino de Pino' and e_shops_visible = 1), (select e_categories_id from e_categories where e_categories_code = 'RIST' and e_categories_visible = 1), 0, 1);
insert into r_e_shops_e_categories(r_e_shops_e_categories_e_shops_id, r_e_shops_e_categories_e_categories_id, r_e_shops_e_categories_main_category, r_e_shops_e_categories_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Lo sviluppatore convinto' and e_shops_visible = 1), (select e_categories_id from e_categories where e_categories_code = 'SPRO' and e_categories_visible = 1), 1, 1);

/*Insert 7: r_e_shops_e_files */
insert into r_e_shops_e_files(r_e_shops_e_files_e_shops_id, r_e_shops_e_files_e_files_id, r_e_shops_e_files_main_picture, r_e_shops_e_files_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_files_id from e_files where e_files_path = '/pictures/shops/00000001.jpg' and e_files_visible = 1), 0, 1);
insert into r_e_shops_e_files(r_e_shops_e_files_e_shops_id, r_e_shops_e_files_e_files_id, r_e_shops_e_files_main_picture, r_e_shops_e_files_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_files_id from e_files where e_files_path = '/pictures/shops/00000002.jpg' and e_files_visible = 1), 1, 1);
insert into r_e_shops_e_files(r_e_shops_e_files_e_shops_id, r_e_shops_e_files_e_files_id, r_e_shops_e_files_main_picture, r_e_shops_e_files_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Er Vino de Pino' and e_shops_visible = 1), (select e_files_id from e_files where e_files_path = '/pictures/shops/00000003.jpg' and e_files_visible = 1), 0, 1);
insert into r_e_shops_e_files(r_e_shops_e_files_e_shops_id, r_e_shops_e_files_e_files_id, r_e_shops_e_files_main_picture, r_e_shops_e_files_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Er Vino de Pino' and e_shops_visible = 1), (select e_files_id from e_files where e_files_path = '/pictures/shops/00000004.jpg' and e_files_visible = 1), 0, 1);
insert into r_e_shops_e_files(r_e_shops_e_files_e_shops_id, r_e_shops_e_files_e_files_id, r_e_shops_e_files_main_picture, r_e_shops_e_files_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Er Vino de Pino' and e_shops_visible = 1), (select e_files_id from e_files where e_files_path = '/pictures/shops/00000005.jpg' and e_files_visible = 1), 1, 1);
insert into r_e_shops_e_files(r_e_shops_e_files_e_shops_id, r_e_shops_e_files_e_files_id, r_e_shops_e_files_main_picture, r_e_shops_e_files_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Er Vino de Pino' and e_shops_visible = 1), (select e_files_id from e_files where e_files_path = '/pictures/shops/00000006.jpg' and e_files_visible = 1), 0, 1);
insert into r_e_shops_e_files(r_e_shops_e_files_e_shops_id, r_e_shops_e_files_e_files_id, r_e_shops_e_files_main_picture, r_e_shops_e_files_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Lo sviluppatore convinto' and e_shops_visible = 1), (select e_files_id from e_files where e_files_path = '/pictures/shops/00000007.jpg' and e_files_visible = 1), 1, 1);

/*Insert 8: e_delivery_routes */
insert into e_delivery_routes(e_delivery_routes_e_shops_id, e_delivery_routes_e_cities_id, e_delivery_routes_price, e_delivery_routes_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_cities_id from e_cities where e_cities_description like '%Magnano in Riviera%'), 0, 1);
insert into e_delivery_routes(e_delivery_routes_e_shops_id, e_delivery_routes_e_cities_id, e_delivery_routes_price, e_delivery_routes_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_cities_id from e_cities where e_cities_description like '%Tarcento%'), 2, 1);
insert into e_delivery_routes(e_delivery_routes_e_shops_id, e_delivery_routes_e_cities_id, e_delivery_routes_price, e_delivery_routes_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_cities_id from e_cities where e_cities_description like '%Artegna%'), 2, 1);
insert into e_delivery_routes(e_delivery_routes_e_shops_id, e_delivery_routes_e_cities_id, e_delivery_routes_price, e_delivery_routes_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_cities_id from e_cities where e_cities_description like '%Buja%'), 2, 1);
insert into e_delivery_routes(e_delivery_routes_e_shops_id, e_delivery_routes_e_cities_id, e_delivery_routes_price, e_delivery_routes_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_cities_id from e_cities where e_cities_description like '%Treppo Grande%'), 2, 1);
insert into e_delivery_routes(e_delivery_routes_e_shops_id, e_delivery_routes_e_cities_id, e_delivery_routes_price, e_delivery_routes_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_cities_id from e_cities where e_cities_description like '%Cassacco%'), 2, 1);
insert into e_delivery_routes(e_delivery_routes_e_shops_id, e_delivery_routes_e_cities_id, e_delivery_routes_price, e_delivery_routes_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_cities_id from e_cities where e_cities_description like '%Gemona%'), 3, 1);
insert into e_delivery_routes(e_delivery_routes_e_shops_id, e_delivery_routes_e_cities_id, e_delivery_routes_price, e_delivery_routes_visible) values ((select e_shops_id from e_shops where e_shops_name = 'Il pesce di Francesco' and e_shops_visible = 1), (select e_cities_id from e_cities where e_cities_description like '%Tricesimo%'), 3, 1);